CREATE TABLE IF NOT EXISTS TROLE
(
	ROL_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ROL_NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS TUSER
(
    USER_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
	USER_GOOGLE_ID VARCHAR(100),
    USER_NAME VARCHAR(50),
    USER_LASTNAME VARCHAR(50),
    USER_MAIL VARCHAR(50),
    ROL_ID SMALLINT,

    CONSTRAINT FK_ROL_ID FOREIGN KEY (ROL_ID) REFERENCES TROLE (ROL_ID)
);

CREATE TABLE IF NOT EXISTS TBUILDING
(
    BUILD_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    BUILD_ADDRES VARCHAR(100),
    BUILD_NAME VARCHAR(100),
    BUILD_ZIPCODE MEDIUMINT,
    BUILD_REGION VARCHAR(100),
    BUILD_COUNTRY VARCHAR(100),
    BUILD_PHONE VARCHAR(20),
    BUILD_LATITUDE DOUBLE,
    BUILD_LONGITUDE DOUBLE,
    BUILD_IMG_URL VARCHAR(500),
    BUILD_URL VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS TROOM
(
    ROOM_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ROOM_NAME VARCHAR(100),
    BUILD_ID SMALLINT,

    CONSTRAINT FK_BUILD_ID FOREIGN KEY (BUILD_ID) REFERENCES TBUILDING (BUILD_ID)
);

CREATE TABLE IF NOT EXISTS TEVENT_TYPE
(
    ETYPE_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ETYPE_NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS TEVENT
(
    EVENT_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    EVENT_NAME VARCHAR(100),
    EVENT_SPEAKER VARCHAR(100),
    EVENT_DESC VARCHAR(300),
    USER_ID SMALLINT,
    ETYPE_ID SMALLINT,
    ROOM_ID SMALLINT,

    CONSTRAINT FK_ETYPE_ID FOREIGN KEY (ETYPE_ID) REFERENCES TEVENT_TYPE (ETYPE_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES TUSER (USER_ID),
    CONSTRAINT FK_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES TROOM (ROOM_ID)
);

CREATE TABLE IF NOT EXISTS TSCHEDULE
(
    SCHEDULE_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    SCHEDULE_START_HOUR TIME,
    SCHEDULE_END_HOUR TIME,
    SCHEDULE_START_DATE DATE,
    SCHEDULE_END_DATE DATE,
    SCHEDULE_DAY_MONDAY BOOL,
    SCHEDULE_DAY_TUESDAY BOOL,
    SCHEDULE_DAY_WEDNESDAY BOOL,
    SCHEDULE_DAY_THURSDAY BOOL,
    SCHEDULE_DAY_FRIDAY BOOL,
    SCHEDULE_DAY_SATURDAY BOOL,
    SCHEDULE_DAY_SUNDAY BOOL,
    EVENT_ID SMALLINT,

    CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES TEVENT(EVENT_ID)
);

