CREATE TABLE IF NOT EXISTS TROLE
(
	ROL_ID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ROL_NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS TUSER
(
	USR_GOOGLE_ID VARCHAR(100),
    USR_NAME VARCHAR(50),
    ROL_ID SMALLINT,
    MAIL VARCHAR(50),

    CONSTRAINT FK_ROL_ID FOREIGN KEY (ROL_ID) REFERENCES TROLE (ROL_ID)
);